# Generated by Django 5.0.6 on 2024-05-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='null', upload_to='articles'),
        ),
    ]
