# Generated by Django 5.0.6 on 2024-05-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0002_post_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                ("image", models.ImageField(default="null", upload_to="base_img")),
            ],
        ),
    ]
